# Generated by Django 2.2.19 on 2022-07-12 20:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_value', models.IntegerField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(limit_value=100, message='Максимальный приоритет 100'), django.core.validators.MinValueValidator(limit_value=0, message='Самый низкий приоритет 0')])),
                ('condition', models.CharField(choices=[(1, 'created'), (2, 'launched'), (3, 'stopped')], default=1, help_text='Выбери статус задания', max_length=20, verbose_name='Статус задания')),
                ('pub_date', models.DateTimeField(auto_now_add=True, help_text='Дата присвоена автоматически', verbose_name='Дата создания задания')),
            ],
            options={
                'verbose_name': 'Приоритет заданий',
            },
        ),
    ]
