# Generated by Django 2.2.19 on 2022-07-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priorities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='condition',
            field=models.CharField(choices=[('created', 'created'), ('launched', 'launched'), ('stopped', 'stopped')], default='created', help_text='Выбери статус задания', max_length=20, verbose_name='Статус задания'),
        ),
    ]
