# Generated by Django 2.2.19 on 2022-07-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priorities', '0002_auto_20220712_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=20, verbose_name='Фамилия')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
                'ordering': ('last_name',),
            },
        ),
        migrations.AddField(
            model_name='priority',
            name='creators',
            field=models.ManyToManyField(related_name='creators', to='priorities.Creator', verbose_name='Исполнители'),
        ),
    ]
